server:
  port: 8080
  servlet:
    context-path: /blog
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.177.1:3306/blog?serverTimeZone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: blog
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      #配置初始化大小/最小/最大
      initial-size: 5
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0 # Redis 连接超时时间，单位：毫秒。
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        max-idle: 8 # 默认连接数最小空闲的连接数，默认为 8 。使用负数表示没有限制。
        min-idle: 0 # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        max-wait: -1 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制。
  jackson:
    default-property-inclusion: non_null
  cache:
    #设置缓存的类型，使用redis来做缓存
    type: redis
    redis:
      time-to-live: 600000
mybatis:
  #mapper目录
  mapper-locations: classpath:mapper/*.xml
  #扫描model包
  type-aliases-package: top.hhhhhgx.blog.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #打印sql执行语句记录
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  #指定数据库
  helper-dialect: mysql
  #设置合理分页；pageNum<=0就查第一页；大于页数就查最后一页。
  reasonable: true
  #如果参数带有pageNum和pageSize就默认分页
  support-methods-arguments: true
  params: count=countsql

logging:
  #指定配置文件
  config: classpath:logback.xml
  file:
    #文件的保存目录
    path: /usr/ideaLog/blog

shiro:
  jwt:
    encryptJWTKey: 123456
    tokenExpireTime: 180000 #1800